<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Basket.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Basket.Core\Basket.Core.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EShop.Caching\EShop.Caching.csproj" />
  </ItemGroup>
</Project>
