<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Basket.Api</RootNamespace>
    <UserSecretsId>eshop-basket-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Basket.Infrastructure\Basket.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EShop.ServiceDefaults\EShop.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
