<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>EShop.Gateway</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\EShop.Caching\EShop.Caching.csproj" />
  </ItemGroup>
</Project>
